# Generated by Django 4.0.2 on 2022-04-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=25, unique=True)),
                ('robot_channel', models.TextField()),
                ('ui_channel', models.TextField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('hall', models.IntegerField(default=0)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route')),
            ],
        ),
    ]
