# Generated by Django 4.0.2 on 2022-03-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=25, unique=True)),
                ('robot_channel', models.TextField()),
                ('ui_channel', models.TextField(null=True)),
            ],
        ),
    ]
