# Generated by Django 4.0.2 on 2022-04-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='hall',
            field=models.TextField(default='BASE'),
        ),
    ]
