# PiCar Configuration
PICAR_MAX_SPEED = 95
PICAR_MED_SPEED = 75

# Line Follower Configuration
LINE_FOLLOWER_REFERENCES = [60, 60, 60, 60, 60]

# Ultrasonic Sensor Configuration
ULTRASONIC_SENSOR_CHANNEL = 16
ULTRASONIC_SENSOR_MIN_DISTANCE = 25

# Color Sensor Configuration
COLOR_SENSOR_INTEGRATION_TIME = 2.4
COLOR_SENSOR_GAIN = 60

COLOR_SENSOR_BLUE_VALUE = 20000
COLOR_SENSOR_RED_VALUE = 3100
