# PiCar Configuration
PICAR_MAX_SPEED = 95
PICAR_MED_SPEED = 65
PICAR_CROSSPATH_SPEED = 50

# PiCar Wheels Configuration
PICAR_TURNING_OFFSET = 23
PICAR_FORWARD_A = 1
PICAR_FORWARD_B = 1

# Picar Turn Steps
PICAR_A_STEP = 3
PICAR_B_STEP = 6
PICAR_C_STEP = 12
PICAR_D_STEP = 45

# Line Follower Configuration
LINE_FOLLOWER_REFERENCES = [55, 55, 55, 55, 55]
LINE_FOLLOWER_MAX_OFF_TRACK_COUNT = 70

# Ultrasonic Sensor Configuration
ULTRASONIC_SENSOR_CHANNEL = 16
ULTRASONIC_SENSOR_MIN_DISTANCE = 25

# Color Sensor Configuration
COLOR_SENSOR_INTEGRATION_TIME = 2.4
COLOR_SENSOR_GAIN = 60

COLOR_SENSOR_BLUE_VALUE = 20000
COLOR_SENSOR_RED_VALUE = 3100
