# Generated by Django 4.0.2 on 2022-04-12 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_room', models.CharField(max_length=5)),
                ('dest_room', models.CharField(max_length=5)),
                ('route', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('return_route', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'unique_together': {('origin_room', 'dest_room')},
            },
        ),
    ]
