# Generated by Django 4.0.2 on 2022-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='dest_room',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin_room',
            field=models.CharField(max_length=10),
        ),
    ]
