<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-04-25 19:27
=======
# Generated by Django 4.0.2 on 2022-04-26 15:17
>>>>>>> 4b36a36c1c2484eb6ac2b81b2f1f7bcd63327308

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='dest_room',
<<<<<<< HEAD
            field=models.CharField(max_length=10),
=======
            field=models.TextField(),
>>>>>>> 4b36a36c1c2484eb6ac2b81b2f1f7bcd63327308
        ),
        migrations.AlterField(
            model_name='route',
            name='origin_room',
<<<<<<< HEAD
            field=models.CharField(max_length=10),
=======
            field=models.TextField(),
>>>>>>> 4b36a36c1c2484eb6ac2b81b2f1f7bcd63327308
        ),
    ]
